# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python


trigger:
  branches:
    include:
      - master
  paths:
    include: 
      - dsnake4-react-phaser/*

jobs:
- job:
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      node_12_x:
        node_version: 12.x
  steps:
    - task: NodeTool@0 
      inputs:
        versionSpec: $(node_version)
    # Copy files
    - script: cp .prod.env .env
      workingDirectory: dsnake4-react-phaser
      displayName: Transform .env file for Production
    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'
      workingDirectory: dsnake4-react-phaser
    - task: CopyFiles@2
      inputs:
        Contents: 'dsnake4-react-phaser/build/**' # Pull the build directory (React)
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs: 
        pathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
        ArtifactName: 'dsnake4-react-phaser' # output artifact named snake-app
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    - task: UniversalPackages@0
      inputs:
        command: 'publish'
        publishDirectory: '$(Build.ArtifactStagingDirectory)'
        feedsToUsePublish: 'internal'
        vstsFeedPublish: '1ec9d425-a99e-48b2-983f-b31bc9281b63/1a0470b0-ee13-4441-b6a5-42df5b2d73e7'
        vstsFeedPackagePublish: 'dsnake4-react-phaser'
        versionOption: 'patch'
        verbosity: 'Warning'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
# - job: python-snake
#   pool:
#     vmImage: 'ubuntu-latest'
#   strategy:
#     matrix:
#       Python35:
#         python.version: '3.5'
#       Python36:
#         python.version: '3.6'
#       Python37:
#         python.version: '3.7'

#   steps:
#   - task: UsePythonVersion@0
#     inputs:
#       versionSpec: '$(python.version)'
#     displayName: 'Use Python $(python.version)'

#   - script: |
#       python -m pip install --upgrade pip
#       pip install pipenv
#       pipenv install
#       # pip install -r requirements.txt
#     displayName: 'Install dependencies'

#   - script: |
#       pip install pytest pytest-azurepipelines
#       pytest
#     displayName: 'pytest'
