# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:
- job:
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      node_12_x:
        node_version: 12.x
  steps:
    - task: NodeTool@0 
      inputs:
        versionSpec: $(node_version)
    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'
      workingDirectory: dsnake4-phaser
    - task: CopyFiles@2
      inputs:
        Contents: 'dsnake4-phaser/build/**' # Pull the build directory (React)
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs: 
        pathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
        ArtifactName: 'snake-app' # output artifact named snake-app

# - job: python-snake
#   pool:
#     vmImage: 'ubuntu-latest'
#   strategy:
#     matrix:
#       Python35:
#         python.version: '3.5'
#       Python36:
#         python.version: '3.6'
#       Python37:
#         python.version: '3.7'

#   steps:
#   - task: UsePythonVersion@0
#     inputs:
#       versionSpec: '$(python.version)'
#     displayName: 'Use Python $(python.version)'

#   - script: |
#       python -m pip install --upgrade pip
#       pip install pipenv
#       pipenv install
#       # pip install -r requirements.txt
#     displayName: 'Install dependencies'

#   - script: |
#       pip install pytest pytest-azurepipelines
#       pytest
#     displayName: 'pytest'

